# Generated by Django 2.0.7 on 2019-01-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='value',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(max_length=216, unique=True),
        ),
    ]
